# Generated by Django 2.0.5 on 2018-12-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do ponto turístico', max_length=150, verbose_name='Ponto Turístico')),
                ('descricacao', models.TextField(help_text='Descrição do ponto turístico', verbose_name='Descrição')),
                ('status', models.BooleanField(default=False, help_text='Selecione para ativar este ponto turístico', verbose_name='Status')),
            ],
        ),
    ]
