# Generated by Django 2.0.5 on 2018-12-08 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0003_pontoturistico_avaliacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name': 'Ponto Turístico', 'verbose_name_plural': 'Pontos Turísticos'},
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco', verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
