# Generated by Django 2.0.5 on 2018-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181208_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='status',
            field=models.BooleanField(default=False, help_text='Selecione para ativar este ponto turístico', verbose_name='Publicado'),
        ),
    ]
