# Generated by Django 2.0.5 on 2018-12-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default='Brasil', max_length=70, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
    ]
