# Generated by Django 2.0.5 on 2018-12-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Atração', max_length=150, verbose_name='Atração')),
                ('descricacao', models.TextField(help_text='Descrição da atração', verbose_name='Descrição')),
                ('horario_func', models.TextField(verbose_name='Horário de Funcionamento')),
                ('idade_minima', models.IntegerField(verbose_name='Idade Miníma')),
            ],
        ),
    ]
